
# Activate the environmet to run the code using "source activate bttb"
# or "activate bttb" on Windows.
name: bttb
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.8
    - pip
    - numpy
    - scipy
    - matplotlib
    - jupyter
    - pytest
    - pytest-cov